#!/bin/sh

i() {
	echo -n '`'
    cat ./include/$1 | sed 's/`/``/g'
	echo -n '`'
}

cat > ./include.go <<EOF
package main

const css = `i reset.css` + `i blog.css`

const baseTemplText = `i base.html`

const feedTemplText = `i feed.atom`
EOF
